apiVersion : apps/v1
kind: Deployment
metadata:
  name: kedaexemplo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kedaexemplo
  template:
    metadata:
      labels:
        app: kedaexemplo
    spec:
      containers:
        - name: kedaexemplo
          image: acrdemoptc.azurecr.io/kedaexemplo:latest
          ports:
          - containerPort: 80
          env:
          - name: ServiceBus__Connection
            value: "Endpoint=sb://csa-demo.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=ARIB8triKTuZSFdHnKk0MsxujOLjbnKiB1duyWK9byU="
      imagePullSecrets:
        - name: secretkey
---
apiVersion: v1
kind: Service
metadata:
    name: kedaexemplo
spec:
    type: ClusterIP
    ports:
    - port: 80 
    selector:
        app: kedaexemplo