apiVersion : apps/v1
kind: Deployment
metadata:
  name: kedaexemplo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kedaexemplo
  template:
    metadata:
      labels:
        app: kedaexemplo
    spec:
      containers:
        - name: kedaexemplo
          image: #acr_name#.azurecr.io/container:latest
          ports:
          - containerPort: 80
          env:
          - name: ServiceBus__Connection
            value: "service_bus_endpoint"
      imagePullSecrets:
        - name: secretkey
---
apiVersion: v1
kind: Service
metadata:
    name: kedaexemplo
spec:
    type: ClusterIP
    ports:
    - port: 80 
    selector:
        app: kedaexemplo
