apiVersion : apps/v1
kind: Deployment
metadata:
  name: kedaexemplo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kedaexemplo
  template:
    metadata:
      labels:
        app: kedaexemplo
    spec:
      containers:
        - name: kedaexemplo
          image: tdcdemoacr.azurecr.io/kedaexemplo:latest
          ports:
          - containerPort: 80
          env:
          - name: ServiceBus__Connection
            value: "Endpoint=sb://tdcdemosb.servicebus.windows.net/;SharedAccessKeyName=Ouvir;SharedAccessKey=tTERv+iHU7A99S3OBmvjJut7g4mLS3vKUUvvin4im8Q=;EntityPath=kedafila"
      imagePullSecrets:
        - name: secretkey
---
apiVersion: v1
kind: Service
metadata:
    name: kedaexemplo
spec:
    type: ClusterIP
    ports:
    - port: 80 
    selector:
        app: kedaexemplo
