apiVersion: v1
kind: Secret
metadata:
  name: kedaexemploscaledobjectsecret
data:
  ServiceBusAzure: RW5kcG9pbnQ9c2I6Ly9jc2EtZGVtby5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPVJvb3RNYW5hZ2VTaGFyZWRBY2Nlc3NLZXk7U2hhcmVkQWNjZXNzS2V5PUFSSUI4dHJpS1R1WlNGZEhuS2swTXN4dWpPTGpibktpQjFkdXlXSzlieVU9
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: kedaexemplo-scaledobject-auth
spec:
  secretTargetRef:
    - parameter: connection
      name: kedaexemploscaledobjectsecret
      key: ServiceBusAzure
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kedaexemplo-scaledobject
spec:
  scaleTargetRef:
    name: kedaexemplo
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
    metadata:
      namespace: csa-demo
      queueName: kedafila
      messageCount: "5"
    authenticationRef:
      name: kedaexemplo-scaledobject-auth