apiVersion: v1
kind: Secret
metadata:
  name: kedaexemploscaledobjectsecret
data:
  ServiceBusAzure: RW5kcG9pbnQ9c2I6Ly90ZGNkZW1vc2Iuc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1PdXZpcjtTaGFyZWRBY2Nlc3NLZXk9dFRFUnYraUhVN0E5OVMzT0JtdmpKdXQ3ZzRtTFMzdktVVXZ2aW40aW04UT07RW50aXR5UGF0aD1rZWRhZmlsYQ==
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: kedaexemplo-scaledobject-auth
spec:
  secretTargetRef:
    - parameter: connection
      name: kedaexemploscaledobjectsecret
      key: ServiceBusAzure
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kedaexemplo-scaledobject
spec:
  scaleTargetRef:
    name: kedaexemplo
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
    metadata:
      namespace: tdcdemosb
      queueName: kedafila
      messageCount: "5"
    authenticationRef:
      name: kedaexemplo-scaledobject-auth
